version: "3.9"

services:
  web:
    container_name: southville-forge-site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    driver: bridge


