import type { Metadata } from "next";
import { Roboto, Staatliches, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "../components/ChatProvider";
import SiteNav from "../components/SiteNav";

// Body text font
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

// Headings font
const staatliche = Staatliches({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

// Serif font for ForgeText flicker
const cormorant = Cormorant_Garamond({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/SF4.png",
    shortcut: "/SF4.png",
    apple: "/SF4.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${roboto.variable} ${staatliche.variable} ${cormorant.variable} antialiased text-center`}
      >
        <ChatProvider>
          <SiteNav />
          {children}
        </ChatProvider>
      </body>
    </html>
  );
}
