name: Deploy to Helsinki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Helsinki via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/southville-forge/southville-forge-nextjs
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo "✅ Deploy completed on $(hostname)"
