name: Deploy to Helsinki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Helsinki via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd /home/southville-forge/southville-forge-nextjs
            echo "🔄 Fetching latest code from GitHub..."
            git fetch origin main
            git reset --hard origin/main
            echo "🧹 Cleaning up Docker cache..."
            docker compose down --remove-orphans
            docker system prune -af
            echo "⚙️ Rebuilding containers..."
            docker compose up -d --build
            echo "✅ Deploy completed successfully on $(hostname)"

